name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: java src/algoritmos/Quicksort.java
      - run: java src/algoritmos/RadixSort.java
      - run: java src/algoritmos/BubbleSort.java
      - run: java src/algoritmos/MergeSort.java
      - run: java src/algoritmos/SelectionSort.java